---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "devops_global"
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  imagePullSecrets:
    - name: "registrypullsecret"
  containers:
    - name: "devops-global-generic"
      image: "globaldevtools.bbva.com:5000/piaas/gpipe/devops_global:latest"
      tty: true
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 1Gi
          cpu: 1
      command:
        - cat
